name: call-reusable-workflow
on: workflow_dispatch

jobs:
  job1:
    uses: Vacal4123/test3/.github/workflows/reusable-workflow.yml@main
    with:
      input1: 10

    job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - run: echo ${{ needs.job1.outputs.output1 }}
