name: call-reusable-workflow
on: 
  workflow_dispatch
jobs:
  job1:
    uses: test3/.github/workflows/reusable-workflow.yml@main
    with:
      input1: Hello
      input2: World

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.output1 }}