name: reusable-workflow
on: 
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
      input2:
        required: true
        type: string
    outputs:
      output1:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}


jobs:
  example_job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.result }}
    steps:
      - id: step1
        run: echo "result = ${{ inputs.input1 }} ${{ inputs.input2 }}" >> $GITHUB_OUTPUT